### ISSUE TITLE
Path(/usr/kafka-manager)

### ISSUE THREAD

**Issue by ChristianKniep** [sheepkiller/kafka-manager-docker#2]
Hey there,

I was trying out your Image but it failed with the following error:

```
Yikes! Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [5000 ms]
```

Is `/user/kafka-manager/` correct? To me it seems more like `/kafka-manager`

Cheers
Christian

**Comment by sheepkiller** [comment]
Hi,
Can you please give more details about your environment ?
thanks

**Comment by sheepkiller** [comment]
Hi,

I'm closing this issue. I think it'x fixed by now. Thanks for your report.
