### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by timmartin19** [sheepkiller/kafka-manager-docker#4]
I tried to build the image unfortunately, I got the following error.

```
[info] Packaging /tmp/kafka-manager/target/scala-2.11/kafka-manager_2.11-1.3.0.4-javadoc.jar ...
[info] Done packaging.
[error] File name too long
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 278 s, completed Jan 15, 2016 5:32:22 PM
The command '/bin/sh -c mkdir -p /tmp &&     cd /tmp &&     git clone https://github.com/yahoo/kafka-manager &&     cd /tmp/kafka-manager &&     git checkout ${KM_REVISION} &&     ./sbt clean dist &&     unzip  -d / ./target/universal/kafka-manager-${KM_VERSION}.zip &&     rm -fr /tmp/* /root/.sbt /root/.ivy2' returned a non-zero code: 1
```

Apparently docker has a max filename size of 242 instead of the standard 255.

**Comment by ChristianKniep** [comment]
Same error here... Anyone an idea?

**Comment by sheepkiller** [comment]
Hi, 
Thanks @timmartin19  for reporting this issue. I usually build my images on archlinux/centos so I didn't notice this AURfs limitation - nor on docker hub.
@ChristianKniep it has also, been reported upstream, and you can find a workaround here: https://github.com/yahoo/kafka-manager/issues/76

I'll (try to) fix the issue later today.

thanks
